fixed a bad-am_obj-use bug
angr/angr-management pull request #377
Opened 2021-07-06 16:23 UTC by mahaloz

Fixed a bug in TraceViewer bug.

Closes #376.

2021-07-06 16:26 UTC, mahaloz commented
@rhelmot the AMContainer stuff is as dangerous as it is useful, since all plugins (loaded or not), seem to be able to crash if they handle publish events from an AMContainer and something goes wrong. Ideally, we should probably find a way to either isolate plugins more.

2021-07-06 16:55 UTC, ltfish commented
I think the solution is to add `try: ... except ...` around all callbacks to plugins.

2021-07-06 16:55 UTC, ltfish approved these changes

2021-07-06 16:56 UTC, ltfish requested changes

2021-07-06 16:56 UTC, ltfish commented on angrmanagement/plugins/trace_viewer/qtrace_viewer.py
> +        if self.trace.am_obj is None:
Use `if self.trace.am_none:` instead.

2021-07-06 18:53 UTC, ltfish approved these changes

2021-07-06 18:53 UTC, merged

2021-07-07 04:08 UTC, rhelmot commented
> I think the solution is to add try: ... except ... around all callbacks to plugins.

I architected the plugin manager so that it did its own error handling - did we add any additional callbacks that didn't use the `PluginManager._dispatch` function?

2021-07-07 04:11 UTC, ltfish commented
I don't know. Maybe?

2021-07-07 04:15 UTC, rhelmot commented
Oh, I misunderstood the problem. You're right, we should absolutely add try-except inside am_event.

2021-07-07 04:21 UTC, rhelmot commented
See linked commit. Should prevent future issues from being catastrophic.

2021-07-07 04:22 UTC, ltfish commented
Python 3.11 implements zero-cost exception handling. Performance-wise, adding try-except inside am_event() should be good in the long run.

2021-07-07 04:23 UTC, ltfish commented
@rhelmot Can we print the entire stack trace for the ease of debugging?

2021-07-07 04:26 UTC, rhelmot commented
Currently it looks like this:

```
ERROR   | 2021-07-06 21:20:15,639 | angrmanagement.data.object_container | Error raised from event of (container: Global states list)[<SimState @ 0x4004b0>]
Traceback (most recent call last):
  File "/home/audrey/angr/angr-management/angrmanagement/data/object_container.py", line 26, in am_event
    listener(**kwargs)
  File "<ipython-input-3-1889d8869666>", line 2, in myfunc
    raise Exception('haha')
Exception: haha
```

I don't know how to get python to display a longer backtrace than that. It does print out the exact object container that was used, which should be helpful for debugging...

2021-07-07 06:53 UTC, ltfish commented
`l.exception(..., exc_info=True)`?

2021-07-07 07:28 UTC, rhelmot commented
`exception` has `exc_info=True` by default. that's what distinguishes it from `error`.

```
[+] In [3]: l.exception??
Signature: l.exception(msg, *args, exc_info=True, **kwargs)
Source:   
    def exception(self, msg, *args, exc_info=True, **kwargs):
        """
        Convenience method for logging an ERROR with exception information.
        """
        self.error(msg, *args, exc_info=exc_info, **kwargs)
File:      /usr/lib/python3.8/logging/__init__.py
Type:      method
```